package com.example.btl_tmdt.model;

import com.example.btl_tmdt.dao.InteractionLogDao;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.Date;

@Data
@Document(collection = "interaction_logs")
@AllArgsConstructor
@NoArgsConstructor
public class InteractionLog {
    @Id
    private String id;
    private String userId;
    private String productId;
    private String interactionType; // e.g., "VIEW", "ADD_TO_CART", "PURCHASE", "REVIEW"
    private Integer rating; // Only for "REVIEW" type, otherwise null
    private Date timestamp;

    // Constructor for new interactions (ID will be generated by MongoDB)
    public InteractionLog(String userId, String productId, String interactionType, Integer rating, Date timestamp) {
        this.userId = userId;
        this.productId = productId;
        this.interactionType = interactionType;
        this.rating = rating;
        this.timestamp = timestamp;
    }

    public InteractionLogDao toDao() {new InteractionLogDao(id, userId, productId, interactionType, rating, timestamp);
    }
}